const baseURL = import.meta.env.VITE_API_URL;
export const urlBarbero = `${baseURL}/Barbero`;
export const urlBarberia = `${baseURL}/Barberia`;
export const urlCita = `${baseURL}/Cita`;
export const urlCliente = `${baseURL}/Cliente`;
export const urlComentarios = `${baseURL}/Comentario`;
export const urlEstilos = `${baseURL}/Estilosdecorte`;
export const urlAdm = `${baseURL}/Administrador`;
export const urlReportes = `${baseURL}/Reportes`;
